name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        sdk: ["3.0.0", stable]
    steps:
      - uses: actions/checkout@v4
      - uses: dart-lang/setup-dart@v1
        with:
          sdk: ${{ matrix.sdk }}
      - run: dart pub get
      - run: dart format --output=none --set-exit-if-changed lib test example
        if: matrix.sdk == 'stable'
      - run: dart analyze --fatal-infos
      - run: dart test
